<|ref|>title<|/ref|><|det|>[[230, 85, 920, 170]]<|/det|>
# DIÁRIO DO GOVÉRNO 

<|ref|>text<|/ref|><|det|>[[636, 168, 911, 182]]<|/det|>
PREÇO DÊSTE NÚMERO - 930 

<|ref|>text<|/ref|><|det|>[[55, 193, 320, 243]]<|/det|>
Toda a correspondência, quer oficial, quer rela- tiva a anúncios e à assinatura do Diário do Governo, deve ser dirigida à Administração da Imprensa Nacional. As publicações literárias do que se re- cobam 2 exemplares anunciam-se gratuitamente. 

<|ref|>text<|/ref|><|det|>[[340, 197, 504, 235]]<|/det|>
As 3 séries . . . . . . . . . . . . . . . . . . . .  A 1.º série . . . . . . . . . . . . . . . . . . . A 2.º série . . . . . . . . . . . . . . . . A 3.º série . . . . . . . . . . . . . . . . 

<|ref|>text<|/ref|><|det|>[[360, 230, 617, 243]]<|/det|>
Avulso : Número de duas páginas 530 ;  de mais de duas páginas 530 por cada duas páginas 

<|ref|>text<|/ref|><|det|>[[666, 194, 925, 241]]<|/det|>
O preço dos anúncios (pagamento adiantado)  é de 2500 a linha, acrescido do respectivo im- posto do sêlo. Os anúncios a que se referem os   1.º e 2.º do artigo 2.º do decreto n.º 10:112,  de 24-IX-1924, têm 40 por cento de abatimento. 

<|ref|>sub_title<|/ref|><|det|>[[193, 271, 336, 286]]<|/det|>
## SUMÁRIO 

<|ref|>sub_title<|/ref|><|det|>[[97, 303, 244, 315]]<|/det|>
## Ministério das Finanças : 

<|ref|>text<|/ref|><|det|>[[55, 325, 472, 347]]<|/det|>
Decreto n.º 29:800—Abre um crédito destinado a impressos para o serviço interno aduaneiro. 

<|ref|>text<|/ref|><|det|>[[55, 352, 472, 392]]<|/det|>
Portaria n.º 9:280—Extingue o pôsto especial de despacho de Alverca e cria em sua substituição um em Cabo Ruivo, na área da jurisdição da Alfândega de Lisboa, que se denominará pôsto especial de despacho de Câbo Ruivo. 

<|ref|>sub_title<|/ref|><|det|>[[97, 408, 320, 419]]<|/det|>
## Ministério dos Negócios Estrangeiros : 

<|ref|>text<|/ref|><|det|>[[55, 429, 472, 460]]<|/det|>
Aviso—Torou público ter o Governo Belga aderido à Convenção assinada em: Paris a 31 de Outubro de 1938, modificando a Con- venção Sanitária Internacional de 21 de Junho de 1926. 

<|ref|>sub_title<|/ref|><|det|>[[97, 476, 298, 487]]<|/det|>
## Ministério da Educação Nacional: 

<|ref|>text<|/ref|><|det|>[[55, 497, 472, 537]]<|/det|>
Decreto-lei n.º 29:807 — Promulga várias disposições atinentes a regular o funcionamento das escolas do ensino primário ele- mentar que passaram a. funcionar como oficiais e uniformiza a situação dos professores das referidas escolas. 

<|ref|>text<|/ref|><|det|>[[495, 270, 923, 294]]<|/det|>
ceitua o § único do artigo 36.º do decreto n.º 18:381, de 24 de Maio de 1930. 

<|ref|>text<|/ref|><|det|>[[516, 298, 867, 311]]<|/det|>
Publique-se e cumpra-se como nêle se contém. 

<|ref|>text<|/ref|><|det|>[[495, 315, 923, 339]]<|/det|>
Paços do Governo da República, 5 de Agosto de 1939.—ANTÓNIO DE OLIVEIRA SALAZAR. 

<|ref|>text<|/ref|><|det|>[[574, 345, 775, 356]]<|/det|>
— — — — — — — — — — — — — — — — — — — — — 

<|ref|>sub_title<|/ref|><|det|>[[574, 368, 855, 380]]<|/det|>
## Direcção Geral das Alfandegas. 

<|ref|>text<|/ref|><|det|>[[666, 387, 755, 400]]<|/det|>
1.ª Repartição 

<|ref|>text<|/ref|><|det|>[[676, 408, 744, 419]]<|/det|>
1.ª secção 

<|ref|>text<|/ref|><|det|>[[625, 430, 790, 442]]<|/det|>
Portaria n.º 9:280 

<|ref|>text<|/ref|><|det|>[[495, 450, 923, 524]]<|/det|>
Manda o Governo da República Portuguesa, pelo Mi- nistro das Finanças, que seja extinto o pôsto especial de despacho de Alverca e criado em sua substituição um pôsto especial de despacho em Cabo Ruivo, na área da jurisdição da Alfândega de Lisboa, que se denominará pôsto especial de despacho de Cabo Ruivo. 

<|ref|>text<|/ref|><|det|>[[495, 527, 923, 563]]<|/det|>
Ministério das Finanças, 5 de Agosto de 1939.—Pelo Ministro das Finanças, Adriano Pais da Silva Vaz Serra, Sub-Secretário de Estado das Finanças. 

<|ref|>sub_title<|/ref|><|det|>[[144, 583, 380, 599]]<|/det|>
## MINISTÉRIO DAS FINANÇAS 

<|ref|>sub_title<|/ref|><|det|>[[88, 609, 437, 621]]<|/det|>
## Direcção Geral da Contabilidade Pública 

<|ref|>sub_title<|/ref|><|det|>[[528, 595, 894, 611]]<|/det|>
## MINISTÉRIO DOS NEGÓCIOS ESTRANGEIROS 

<|ref|>text<|/ref|><|det|>[[540, 621, 880, 645]]<|/det|>
Direcção Geral dos Negócios Económicos e Consulares 

<|ref|>sub_title<|/ref|><|det|>[[186, 646, 345, 657]]<|/det|>
## Decreto n.º 29:806 

<|ref|>text<|/ref|><|det|>[[55, 667, 472, 730]]<|/det|>
Com fundamento nas disposições de artigo 35.º e sua alínea d) do decreto-lei n.º 18:381, de 24 de Maio de 1930, depois de ouvido o Ministro das Finanças, nos termos do n.º 1.º do artigo 9.º do decreto n.º 22:470, de 11 de Abril de 1933; 

<|ref|>text<|/ref|><|det|>[[55, 730, 472, 776]]<|/det|>
Usando da faculdade conferida pelo n.º 3.º do ar- tigo 109.º da Constituição, o Govérno decreta e eu pro- mulgo, nos termos do § 2.º do seu artigo 80.º, o se- guinte: 

<|ref|>text<|/ref|><|det|>[[55, 780, 472, 861]]<|/det|>
Artigo 1.º É aberto no Ministério das Finanças, a fa- vor do mesmo Ministério, um crédito especial da quan- tia de 15.000$, destinado a impressos para o serviço interno aduaneiro, devendo a mesma importância ser adicionada à verba: de 465.000$ inscrita no n.º 1) do artigo 287.º, capítulo 15.º, do orçamento do referido Mi- nistério para o ano económico de 1939. 

<|ref|>text<|/ref|><|det|>[[55, 862, 472, 897]]<|/det|>
Art. 2.º É anulada a quantia de 15.000$ na verba de 2:600.000$ inscrita no n.º 1) do artigo 160.º, capí- tulo 10.º, do orçamento mencionado no artigo 1.º 

<|ref|>text<|/ref|><|det|>[[55, 898, 472, 934]]<|/det|>
Este crédito foi registado na Direcção Geral da Con- tabilidade Pública e a minuta do presente decreto foi examinada e visada pelo Tribunal de Contas, como pre- 

<|ref|>text<|/ref|><|det|>[[495, 652, 923, 727]]<|/det|>
Por ordem superior se faz público que, segundo comu- nicação do Governo da República Francesa, directamente dirigida à Legação de Portugal em Paris, o Governo Belga aderiu em 5 de Junho último à Convenção assinada em Paris a 31 de Outubro de 1938, modificando a Conven- ção Sanitária Internacional de 21 de Junho de 1926. 

<|ref|>text<|/ref|><|det|>[[495, 730, 923, 755]]<|/det|>
Lisboa, 29 de Julho de 1939.—Pelo Director Geral, V. da Cunha. 

<|ref|>sub_title<|/ref|><|det|>[[550, 781, 868, 796]]<|/det|>
## MINISTÉRIO DA EDUCAÇÃO NACIONAL 

<|ref|>text<|/ref|><|det|>[[540, 805, 864, 817]]<|/det|>
Direcção Geral do Ensino Primário 

<|ref|>text<|/ref|><|det|>[[620, 833, 800, 844]]<|/det|>
Decreto-lei n.º 29:807 

<|ref|>text<|/ref|><|det|>[[495, 852, 920, 934]]<|/det|>
1. A lei n.º 101, de 30 de Dezembro de 1913, esta- beleceu que é contado para os efeitos de aposentação o tempo de serviço prestado, em escolas primárias par- ticulares que viessem a ser convertidas em oficiais, por professores diplomados, contanto que estes contribuam para a Caixa de Aposentações com as cotas correspon- dentes ao período em que fizeram serviço naquelas

<--- Page Split --->
<|ref|>text<|/ref|><|det|>[[73, 72, 496, 95]]<|/det|>
escolas, e pelo tempo posterior à data em que comeca- tem a contribuir para a mesma Caixa. 

<|ref|>text<|/ref|><|det|>[[72, 95, 496, 193]]<|/det|>
A lei n.° 1:754, de 14 de Fevereiro de 1925, definindo as condições legais para a oficialização de escolas pri- márias criadas ou suscitadas pela iniciativa parti- cular, reconheceu à entidade proprietária do edifício escolar a faculdade de propor para professor oficial efectivo o professor em serviço na escola a converter, desde que seja um diplomado por alguma das escolas normais e tenha três anos de bom e efectivo serviço. 

<|ref|>text<|/ref|><|det|>[[70, 194, 496, 357]]<|/det|>
O decreto-lei n.° 16:423, de 25 de Janeiro de 1929, permitiu aos asilos e Misericórdias propor para profes- sor oficial efectivo o professor em serviço na escola oficializada, ainda que não fosse diplomado pelas es- colas normais primárias, contanto que exercesse o ma- gistério há mais de dez anos e que, pelo número de alunos apresentados anualmente a exame com bons resultados, tivesse dado provas evidentes da sua compe- tência; e logo o decreto-lei n.° 16:485, de 9 de Fevereiro do mesmo ano, determinou que o respectivo despacho fôsse sempre fundamentado e publicado na íntegra no Diário do Governo, bem como a nota dos serviços do nomeado, que aliás não poderia ser colocado em qual- quer outra escola, a não ser que a sua fôsse extinta. 

<|ref|>text<|/ref|><|det|>[[70, 358, 496, 489]]<|/det|>
Porque se chegara longe de mais na concessão, o decreto-lêi n.° 17:754, de 12 de Dezembro de 1929, res- tringiu-a aos professores devidamente habilitados para o ensino primário elementar que tenham exercido o ensino com provado zelo e competência; e o decreto n.° 19:245, de 16 de Janeiro de 1931, que revogou al- gumas disposições da lei n.° 1:754 e os decretos-leis n.° 16:423 e 16:485, limitou a faculdade de oficiali- zação às escolas do ensino primário elementar que ha- jam sido criadas ou mantidas «por qualquer entidade de utilidade pública». 

<|ref|>text<|/ref|><|det|>[[70, 490, 496, 586]]<|/det|>
Ainda com as restrições resultantes dos decretos-leis n.° 17:754 e 19:245, o regime de oficialização de es- colas do ensino primário elementar não satisfaz às exigências de uma boa técnica administrativa, pois que por êle se concedem aos professores direitos só jus- tificados a partir do seu ingresso nos quadros do fun- cionalismo, e por isso se impõe revogá-lo, sem prejuízo dos direitos adquiridos na sua vigência. 

<|ref|>text<|/ref|><|det|>[[70, 597, 496, 679]]<|/det|>
2. Acautelados dêste modo os interêsses do Estado, deve atender-se à situação criada aos professores de al- gumas, poucas, escolas que, em conseqüência de diver- sos diplomas legais, de há muito passaram a funcionar como oficiais: a do Asilo de Infância Desvalida, em Elvas, e a escola de dois lugares da Casa Pia, em Evora. 

<|ref|>text<|/ref|><|det|>[[70, 681, 496, 763]]<|/det|>
Embora fundamentados em considerandos idênticos aos de outros diplomas que determinaram a oficializa- ção de escola em diversos estabelecimentos, não se empregou na parte dispositiva daqueles a terminologia própria do acto de oficialização, e por isso se suscita- ram dúvidas sôbre os direitos dos professores nomeados pelos citados decretos. 

<|ref|>text<|/ref|><|det|>[[70, 764, 496, 821]]<|/det|>
O princípio da igualdade de todos perante a lei im- põe que aos professores em serviço naqueles lugares no momento da oficialização de facto sejam reconhecidos os mesmos direitos conferidos aos professores das es- colas oficializadas. 

<|ref|>text<|/ref|><|det|>[[70, 836, 496, 884]]<|/det|>
3. A lei n.° 1:969, de 20 de Maio de 1938, determina, na sua base VIII, que a instalação das escolas do ensino primário deverá dispor de cantina, forma de assistên- cia educativa cujo desenvolvimento muito há-de con- 

<|ref|>text<|/ref|><|det|>[[520, 73, 945, 121]]<|/det|>
tribuir para a freqüência escolar, principalmente nos meios rurais, e para a qual a contribuição da inicia- tiva particular, afirmada em alguns exemplos dignos de ser imitados, deve estimular-se. 

<|ref|>text<|/ref|><|det|>[[520, 122, 945, 226]]<|/det|>
Se se considerar que as despesas de instalação e sus- tentação de uma cantina são amplamente superiores às da construção de uma sala de aula, cuja doação é fundamento legal para a faculdade reconhecida no doa- dor de propor o agente do ensino, há-de reconhecer-se que, por maioria de razão, se justifica concedê-la aos instituidores dos fundos suficientes para instalação e funcionamento de uma cantina, incomparávelmente mais dispendiosos. 

<|ref|>text<|/ref|><|det|>[[520, 228, 945, 357]]<|/det|>
Dentro do mesmo pensamento, as exigências da edu- cação popular levam a reconhecer às associações de beneficência e de educação legalmente autorizadas que deixem de poder sustentar o ensino em escolas cuja criação o recenseamento escolar exija a faculdade de proporem para os lugares que venham a ser criados os agentes do ensino que nêles estejam prestando serviço, desde que sejam diplomados para o magistério oficial e aquelas, mantendo ali uma cantina, ponham à dis- posição do Estado as respectivas instalações e material escolar. 

<|ref|>text<|/ref|><|det|>[[520, 376, 945, 424]]<|/det|>
Usando da faculdade conferida pela 2.ª parte do n.º 2.º do artigo 109.º da Constituição, o Governo de- creta e eu promulgo, nos termos do § 2.º do artigo 80.º, para valer como lei, o seguinte: 

<|ref|>text<|/ref|><|det|>[[520, 428, 945, 488]]<|/det|>
Artigo 1.º São revogados a lei n.º 101, de 30 de De- zembro de 1913, o decreto-lei n.º 17:754, de 12 de De- zembro de 1929, e o decreto n.º 19:245, de 16 de Ja- neiro.de 1931, salvaguardando-se os direitos adquiridos durante a sua vigência. 

<|ref|>text<|/ref|><|det|>[[520, 490, 945, 537]]<|/det|>
Art. 2.º Consideram-se para todos os efeitos legais como oficializadas as escolas criadas pelos decretos-leis n.º 11:245, de 17 de Novembro de 1925, e n.º 11:413, de 20 de Janeiro de 1926. 

<|ref|>text<|/ref|><|det|>[[520, 539, 945, 610]]<|/det|>
Art. 3.º É extensiva aos beneméritos que em favor do Estado instituírem fundos suficientes para a insta- lação e sustentação de cantinas junto das escolas pri- márias oficiais a faculdade concedida aos doadores de edifícios escolares pelo artigo 16.º do decreto-lei n.º 19:531, de 30 de Março de 1931. 

<|ref|>text<|/ref|><|det|>[[520, 610, 945, 727]]<|/det|>
Art. 4.º É atribuída às associações de assistência e educação legalmente reconhecidas, com ou sem inter- nato, que deixem de poder sustentar o ensino em es- colas cuja criação o recenseamento escolar exija, mas ponham à disposição do Estado a respectiva instalação e material escolar em boas condições higiénicas e di- dácticas e nelas mantenham uma cantina, a faculdade de proporem o respectivo agente de ensino, desde que seja diplomado para o magistério oficial e ali exerça funções há mais de cinco anos com exemplar conduta. 

<|ref|>text<|/ref|><|det|>[[520, 728, 945, 800]]<|/det|>
Art. 5.º A faculdade a que se referem os artigos 3.º e 4.º será usada logo que se efective o acto de doação, independentemente dos prazos normais estabelecidos para o provimento das escolas, e os professores ou re- gentes nomeados entrarão imediatamente em exercício sempre que o respectivo lugar esteja livre. 

<|ref|>text<|/ref|><|det|>[[536, 802, 890, 813]]<|/det|>
Publique-se e cumpra-se como nêle se contém. 

<|ref|>text<|/ref|><|det|>[[520, 815, 945, 887]]<|/det|>
Paços do Govêrno da República, 5 de Agosto de 1939.—ANTÔNIO DE OLIVEIRA SALAZAR—Mário Pnis de Sousa—Manuel Rodrigues Júnior—Manuel Ortins de Bettencourt—Duarte Pacheco—Antônio Faria Carneiro Pacheco—João Pinto da Costa Leite—Ra- fael da Silva Neves Duque.

<--- Page Split --->
